### ISSUE TITLE
Update problem with 0.3.0

### ISSUE THREAD

**Issue by HeresJonny** [fnagel/fe_performance#2]
Typo3 6.1.2
fe_performance 0.2.0

"Error while updating extension
Your TYPO3 version is higher than allowed. You can use TYPO3 versions 6.0.0 - 6.0.7"

I have a feeling that's the opposite of what you want to happen....

**Comment by fnagel** [comment]
Another update in TER: http://typo3.org/extensions/repository/view/fe_performance

**Comment by HeresJonny** [comment]
Update von Vorversion auf 0.4 problemlos. Nach De- und Versuch der
Re-Installation:
Your TYPO3 version is higher than allowed. You can use TYPO3 versions
6.1.0 - 6.1.2...
Hätte ich vielleicht mal nicht 6.1.13dev nehmen sollen :P

**Comment by fnagel** [comment]
OK, halten wir fest -- das klappt mal gar nicht. Denn die 6.1.13 wäre ja eigentlich in Ordnung. Nur die frühen Versionen von 6.0 und 6.1 haben den Bug.

Version 6.0 ist ja mittlerweile eh deprecated also fliegt das einfach insgesamt raus:

````
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.1.3-6.2.99',
		),
		'conflicts' => array(
			'scriptmerger' => '',
		),
	),
````

**Comment by HeresJonny** [comment]
Wo Du gerade da bist :-) ...
Boostrap hat einen sog. "Live"-Modus - bin mir nicht 100% sicher, was da
passiert, aber möglicherweise ähnliches?
http://t3bootstraptv.de/de/konfiguration/live-modus/

**Comment by fnagel** [comment]
Versteh gerade nicht den Zusammenhang.

**Comment by fnagel** [comment]
New version is compatible with TYPO3 CMS 7.x and removed support for < 6.2. 
So this is no longer an issue.
