### ISSUE TITLE
PHP dependancy

### ISSUE THREAD

**Issue by derghostface** [fnagel/fe_performance#4]
It would be good if the PHP dependancy could be raised to 7.3 as TYPO3 9.5 officially supports this version.

Currently you aren't able to install the extension with composer and PHP 7.3.

**Comment by fnagel** [comment]
Can you confirm the extension works with PHP 7.3? I'm not able to test this for now.

**Comment by MatthiasPeltzer** [comment]
yes i can confirm this. works on my live server (without composer)

**Comment by fnagel** [comment]
Nice. Good to have another confirmation. Thanks for the feedback!
