### ISSUE TITLE
Release for TYPO3 11

### ISSUE THREAD

**Issue by criwe** [fnagel/fe_performance#5]
Hi,
is an release for TYPO3 11 planed?
Thanks!
Regards,
Christoph

**Comment by fnagel** [comment]
Yes, there is already an adjusted branch, see https://github.com/fnagel/fe_performance/tree/typo3-11

I did not have the time / project to test every feature for a final release. Any feedback is very welcome!

**Comment by criwe** [comment]
Thanks!
Well, a first brief test did´t do well -> JS crashed, no html-code-minification.
If you want to have a look, we can have a call later or next week.
Best,
Christoph

**Comment by fnagel** [comment]
Regarding crashing JS I need more info. There haven't been much changes at all: https://github.com/fnagel/fe_performance/compare/typo3-11

HTML minification has been removed, see https://github.com/fnagel/fe_performance/commit/0ef8949e6f052ca47c36c88d75eb562ad5192985

Reasons: 1) underlying TYPO3 functionality has changed and it's unclear how to migrate this 2) the implementation with regex always had its issues 3) Using GZIP compression is widely available and should do a better job in general
Anyway, if you find a way to do this in TYPO3 11 I would consider re-add it.

We can do a call later today...

**Comment by criwe** [comment]
Ok, thanks for the call.

What we found out: reason was minifying of allready minifed files.

Regards,
Christoph

**Comment by fnagel** [comment]
Let's keep this open as the final release needs to be done...

**Comment by fnagel** [comment]
Just released version 2.0.0 with TYPO3 11 support.

@criwe FYI (...and HTML minify is back again using a middleware!)

**Comment by criwe** [comment]
@fnagel A little late: but thank you and it is already running successfully
